### ISSUE TITLE
Why does UNO Wifi and Nano Every have a bootloader?

### ISSUE THREAD

**Issue by MCUdude** [arduino/ArduinoCore-megaavr#41]
By looking at the boards.txt and platform.txt it's clear that the microcontroller is flashed through its UPDI line and not through the serial port. If so, why is there a bootloader there? Is it just to get the three blinks when you hit the reset button?

**Comment by facchinm** [comment]
Hi @MCUdude ,
the bootloader is only loaded on the UNO WiFi r2 and its scope (besides the 3 blinks that we needed to add due to popular demand in education :slightly_smiling_face: ) is to allow OTA via the NINA module. The missing patches to fully support this are being merged (a bit slowly but we'll get there)
